language: rust
sudo: false
dist: trusty

cache:
  cargo: true

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: 1.40.0
    - rust: nightly
  allow_failures:
    - rust: nightly

before_script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then
      rustup component add rustfmt
      rustup component add clippy
      cargo install wasm-pack --force
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
      nvm install node
    fi

script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then
      cargo fmt -- --check
      cargo clippy --all-targets --all-features -- -D warnings
    fi
  - cargo check --all
  - cargo test --all-features --all -- --nocapture
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then
      cd yarte_wasm_app && wasm-pack test --node
      cd ../benches && cargo bench
    fi
