language: rust
sudo: false
dist: trusty

cache:
  cargo: false

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: 1.45.0
    - rust: nightly

before_script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then
      rustup component add rustfmt
      rustup component add clippy
    fi
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
  - nvm install node
  - cargo install wasm-pack --force

script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then
      cargo fmt -- --check
      cargo clippy --all-targets --all-features -- -D warnings
      cd delorean && wasm-pack test --node && cd ..
    fi
  - cargo test --all-features --all -- --nocapture
  - |
    cd yarte && cargo test -- --nocapture \
    && cargo test --features bytes-buf    \
    && cargo test --features fixed        \
    && cargo test --features json         \
    && cargo test --features wasm         \
    && cd ..
