# root dir of templates
[main]
dir = "templates"
debug = "code"

# Alias for partials. In call, change the start of partial path with one of this, if exist.
[partials]
alias = "./deep/more/deep"
doc = "./deep/more/doc"
card = "./deep/more/card"

[debug]
# prettyprint themes, put anything for options
theme = "zenburn"
grid = true
header = true
number_line = true
paging = false
short = false
