[package]
name = "utils"
version = "0.1.0"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
edition = "2018"
workspace = ".."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.68"
